import { useEffect } from 'react'
import { useToast } from '../shared/Toast'

const SECTIONS = [
  { key: 'overview',         label: 'Project overview' },
  { key: 'design_direction', label: 'Design direction' },
  { key: 'key_decisions',    label: 'Key decisions' },
  { key: 'open_questions',   label: 'Open questions' },
  { key: 'next_steps',       label: 'Next steps' },
]

function BriefSection({ label, content }) {
  if (!content) return null
  const lines = content.split('\n').filter(Boolean)
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wider mb-2" style={{ color: 'var(--color-brand)' }}>
        {label}
      </h3>
      <div className="flex flex-col gap-1">
        {lines.map((line, i) => (
          <p key={i} className="text-sm leading-relaxed" style={{ color: 'var(--color-text)' }}>
            {line}
          </p>
        ))}
      </div>
    </div>
  )
}

export default function BriefModal({ loading, error, data, onClose }) {
  const toast = useToast()

  useEffect(() => {
    function handle(e) { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handle)
    return () => document.removeEventListener('keydown', handle)
  }, [onClose])

  function handleCopy() {
    if (!data?.brief) return
    const { brief, clientName, projectName } = data
    const lines = [
      `CLIENT BRIEF${clientName ? ` — ${clientName}` : ''}`,
      projectName ? projectName : null,
      `Generated by Studio OS`,
      '',
      ...SECTIONS.flatMap(s => [
        s.label.toUpperCase(),
        brief[s.key] ?? '',
        '',
      ]),
    ].filter(l => l !== null)
    navigator.clipboard.writeText(lines.join('\n'))
    toast('Brief copied to clipboard', 'success')
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ backgroundColor: 'var(--color-overlay)' }}
      onClick={onClose}
    >
      <div
        className="card card-elevated w-full max-w-xl mx-4 animate-fade-up flex flex-col"
        style={{ maxHeight: '85vh' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 pt-5 pb-4 shrink-0" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
          <div className="flex items-center gap-2">
            <div className="w-3.5 h-3.5 rounded-sm" style={{ backgroundColor: 'var(--color-brand)' }} />
            <h2 className="text-base font-medium" style={{ color: 'var(--color-text)' }}>Client brief</h2>
            {data?.clientName && (
              <span className="text-sm" style={{ color: 'var(--color-muted)' }}>— {data.clientName}</span>
            )}
          </div>
          <div className="flex items-center gap-2">
            {data?.brief && (
              <button className="btn text-xs" onClick={handleCopy}>
                <i className="ti ti-copy" style={{ fontSize: 'var(--icon-sm)' }} />
                Copy
              </button>
            )}
            <button
              className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-dark-elevated transition-colors"
              style={{ color: 'var(--color-muted)' }}
              onClick={onClose}
            >
              <i className="ti ti-x" style={{ fontSize: 'var(--icon-md)' }} />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {loading && (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <div
                className="w-8 h-8 rounded-full border-2 animate-spin"
                style={{ borderColor: 'var(--color-brand)', borderTopColor: 'transparent' }}
              />
              <p className="text-sm" style={{ color: 'var(--color-muted)' }}>Claude is reading your brain dump…</p>
            </div>
          )}

          {error && (
            <div className="flex flex-col items-center justify-center py-12 gap-2">
              <i className="ti ti-alert-circle" style={{ fontSize: 'var(--icon-2xl)', color: 'var(--color-red)' }} />
              <p className="text-sm text-center" style={{ color: 'var(--color-muted)' }}>{error}</p>
            </div>
          )}

          {data?.brief && (
            <div className="flex flex-col gap-5">
              {data.projectName && (
                <p className="text-xs" style={{ color: 'var(--color-subtle)' }}>{data.projectName}</p>
              )}
              {SECTIONS.map(s => (
                <BriefSection key={s.key} label={s.label} content={data.brief[s.key]} />
              ))}
              <p className="text-xs pt-2" style={{ color: 'var(--color-subtle)', borderTop: '1px solid var(--border-subtle)' }}>
                Generated from {data.cardCount ?? 'your'} brain dump notes by Claude
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
